import type { Metadata } from "next";

import { Nunito } from "next/font/google";

const nunito = Nunito({ subsets: ["latin"] });

import "./globals.css";
import next from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="my-8">
        <div className={`${nunito.className} container mx-auto`}>
          {children}
        </div>
      </body>
    </html>
  );
}
